### ISSUE TITLE
how to get amount of data which was uploaded and downloaded??

### ISSUE THREAD

**Issue by bizibizi** [pia-foss/vpn-ios#1]

**Comment by ueshiba** [comment]
We have that feature in our backlog for the future but I can't give you a date. Meanwhile, you can implement your method to track the uploaded and downloaded data usage. 

Take a look here to get some inspiration: https://stackoverflow.com/questions/7946699/iphone-data-usage-tracking-monitoring?answertab=votes#tab-top

It would be awesome if you create a pull request so we can include your contribution to the main branch.

Regards,
Jose Blaya.

**Comment by ueshiba** [comment]
@bizibizi you can also find this information and use it as you want in the class **SessionProxy**

The properties are:

- bytesIn
- bytesOut
