### ISSUE TITLE
Failed to download 'PIAWireguard'

### ISSUE THREAD

**Issue by siam009** [pia-foss/vpn-ios#10]
# Summary

### Steps to reproduce
Pod install can not install PIAWireguard 
![Screenshot 2020-10-25 at 4 13 43 PM](https://user-images.githubusercontent.com/33008567/97104304-0f95ef80-16dd-11eb-9479-cb7b73bc996a.png)
![Screenshot 2020-10-25 at 4 13 56 PM](https://user-images.githubusercontent.com/33008567/97104308-16246700-16dd-11eb-8ad0-877a5f57e43b.png)

**Comment by woniupapa** [comment]
I have the same problem with "PIAWireguard", anybody can help me ?

**Comment by ueshiba** [comment]
Hi! 

Please, check if you are using this specific Go version: **1.13.4**

It's a requirement from the WireGuard library to compile using that version.

Regards,
Jose

**Comment by woniupapa** [comment]
Dear ueshiba,
   Tks,I will try it.

**Comment by woniupapa** [comment]
![1711603737184_ pic_hd](https://user-images.githubusercontent.com/2526267/97213614-cfc62980-17fc-11eb-9725-ea09d6c37be7.jpg)

I have used this specific Go version: 1.13.4 in my pic. help me!!! Dear usshiba.

**Comment by ueshiba** [comment]
@woniupapa did you try with a `pod deintegrate` before running the command again?

**Comment by woniupapa** [comment]
@ueshiba yes, I did it, and the same problem.

![1891603817130_ pic_hd](https://user-images.githubusercontent.com/2526267/97334363-a0282780-18b7-11eb-86b9-59efbe3777bc.jpg)
