### ISSUE TITLE
`pod install` fails after cloning from github

### ISSUE THREAD

**Issue by t0mmar** [pia-foss/vpn-ios#11]
# Summary
`pod install` fails after cloning from github

### Steps to reproduce
- clone repository
- run `pod install`

### What is the current bug behaviour?
`pod install` fails to install PIAAccountModule

### What is the expected correct behaviour?
`pod install` succeeds after a fresh clone from github

### Relevant logs and/or screenshots
Error message I receive when running `pod install`:
```
toms-MBP:t0mmar tom$ pod install
Analyzing dependencies
[!] No podspec found for `PIAAccountModule` in `/Users/jose/Projects/PIA/account`
```

### Possible fixes suggested re-mediation
Update paths in Podfile:
```
def shared_main_pods
    pod 'AlamofireImage'
    pod "PIAAccountModule", :path => "/Users/jose/Projects/PIA/account"
    pod "PIARegions", :git => "#{$git_root}/#{$regions_repo}"
    library_by_path('/Users/jose/Projects/PIA')
    #library_by_git('ba3cd1f')
    #library_by_version('~> 1.1.3')
end
```

### Assignees and labels
( please add labels as applicable )    

- [ ] Patched
- [ ] Verified patch

**Comment by ueshiba** [comment]
hi @t0mmar ,

Sorry, I pushed the changes with the local path, you can replace it by:

"#{$git_root}/#{$accounts_repo}"

Regards,
Jose

**Comment by t0mmar** [comment]
@ueshiba 

Thank you.  `library_by_path` is also pointing to a local path - what *should* it point to?
```
    library_by_path('/Users/jose/Projects/PIA')
    #library_by_git('ba3cd1f')
    #library_by_version('~> 1.1.3')
```

**Comment by ueshiba** [comment]
Sorry, you can use the git hash 😓 

`library_by_git('ba3cd1f')`

**Comment by t0mmar** [comment]
TY!

**Comment by ueshiba** [comment]
Don't worry, we will update the repo very soon :)
