### ISSUE TITLE
Build fails: No such module 'Regions'

### ISSUE THREAD

**Issue by t0mmar** [pia-foss/vpn-ios#12]
# Summary

### Steps to reproduce
- clone this repo
- pod install
- update plists, entitlements, etc. with custom Apple identifiers
- build

### What is the current bug behaviour?
I get one error building the PIARegions pod.  It claims that 'Regions' module is not defined.

### What is the expected correct behaviour?
I'm expecting the build to succeed.

### Relevant logs and/or screenshots
![Screen Shot 2020-12-11 at 4 20 12 PM](https://user-images.githubusercontent.com/45108654/101960642-79a31f00-3bcd-11eb-98ab-c090806e3d71.png)

### Possible fixes suggested re-mediation
??? (don't have any)

### Assignees and labels
( please add labels as applicable )    

- [ ] Patched
- [ ] Verified patch

**Comment by ueshiba** [comment]
Hi @t0mmar we are working to improve the process with PIARegions and PIAAcconts. 

Try to run `pod install` and build again, first time we expect you to already have the framework (and should be created with a script inside the PIARegions or PIAAccounts project),

**Comment by t0mmar** [comment]
I attempted to pull down and build https://github.com/pia-foss/mobile-common-regions but I'm getting that same exact error.

**Comment by ueshiba** [comment]
Go to the "Report Navigator" and paste here the full error. Thanks

**Comment by t0mmar** [comment]
Running `pod install` after the initial build fail and building again resolved this one particular issue for me, thank you @ueshiba!

**Comment by ueshiba** [comment]
Yea, as I said, we are working right now to improve this step, but initially, the project thinks you already have the framework created but you need to run pod install and build to generate it.
