### ISSUE TITLE
Build errors: "Server has no member 'dipToken'" 

### ISSUE THREAD

**Issue by t0mmar** [pia-foss/vpn-ios#13]
# Summary

### Steps to reproduce
- clone the vpn-ios repo
- update Podfile to stop pointing to local paths (here is the [Podfile](https://github.com/t0mmar/vpn-ios/blob/purism_master/Podfile) I used)
- pod install
- open 'PIA VPN.xcworkspace' -> Product -> Build
- it fails initially because of some outstanding pod integration issues; the following is a workaround
- pod install
- open 'PIA VPN.xcworkspace' -> Product -> Build

### What is the current bug behaviour?
Results in build errors, mostly about Server not having `dipToken` member.

### What is the expected correct behaviour?
Build succeeds.

### Relevant logs and/or screenshots

![Screen Shot 2020-12-12 at 3 17 26 PM](https://user-images.githubusercontent.com/45108654/101995096-2b555500-3c8d-11eb-83e2-0e3e3ce71bb9.png)

[Build PIA VPN_2020-12-12T15-07-17.txt](https://github.com/pia-foss/vpn-ios/files/5683772/Build.PIA.VPN_2020-12-12T15-07-17.txt)

### Possible fixes suggested re-mediation
Don't know, but I suspect something about those local Pod paths is not picked up in the git references.

### Assignees and labels
( please add labels as applicable )    

- [ ] Patched
- [ ] Verified patch

**Comment by ueshiba** [comment]
Hi @t0mmar , we just updated the repository! I hope your issue is fixed now :)

**Comment by t0mmar** [comment]
@ueshiba 

I'm getting an error installing pods - looks like the Podfile is pointing to `git@codex.londontrustmedia.com:modile/account.git` but that needs a login/password which I don't have:
```
toms-MBP:vpn-ios tom$ pod install
Analyzing dependencies
Pre-downloading: `PIAAccountModule` from `git@codex.londontrustmedia.com:mobile/account.git`, commit `6116a38`
The authenticity of host 'codex.londontrustmedia.com (66.55.155.98)' can't be established.
ECDSA key fingerprint is SHA256:ewaMbdTx/ASjIlc9XpJOKaFOBI/7nSPmO8UK20+DTkY.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
git@codex.londontrustmedia.com's password: 
git@codex.londontrustmedia.com's password: 
git@codex.londontrustmedia.com's password: 

[!] Error installing PIAAccountModule
[!] Failed to download 'PIAAccountModule': [!] /usr/local/bin/git clone git@codex.londontrustmedia.com:mobile/account.git /var/folders/9_/lt3tfvpx4hn929c0_vlbwrbh0000gn/T/d20201215-62051-qhvy9 --template=

Cloning into '/var/folders/9_/lt3tfvpx4hn929c0_vlbwrbh0000gn/T/d20201215-62051-qhvy9'...
Warning: Permanently added 'codex.londontrustmedia.com,66.55.155.98' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
git@codex.londontrustmedia.com: Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

toms-MBP:vpn-ios tom$ code .
toms-MBP:vpn-ios tom$ 

```

**Comment by ueshiba** [comment]
hey @t0mmar , you should use the github addresses for all the modules:

```
    pod "PIAAccountModule", :git => "#{$git_root}/#{$accounts_repo}"
    #pod "PIAAccountModule", :git => "#{$gitlab_kn_root}/#{$accounts_gitlab_repo}", :commit => '6116a38'
    pod "PIARegions", :git => "#{$git_root}/#{$regions_repo}"
    #pod "PIARegions", :git => "#{$gitlab_kn_root}/#{$regions_gitlab_repo}", :commit => '3b9395f'

```

**Comment by t0mmar** [comment]
A little closer I think, but I'm still getting a few new errors:

![Screen Shot 2020-12-15 at 2 42 20 PM](https://user-images.githubusercontent.com/45108654/102270732-f7c03800-3ee3-11eb-97a5-57eab5a47550.png)

[Build PIA VPN_2020-12-15T14-40-29.txt](https://github.com/pia-foss/vpn-ios/files/5698513/Build.PIA.VPN_2020-12-15T14-40-29.txt)

**Comment by ueshiba** [comment]
Hey @t0mmar! sorry, I didn't update the other repositories. Try again, it should work now! 

The version number for the PIAAccounts and PIARegions module should be `1.1.0`

**Comment by t0mmar** [comment]
Builds successfully now on my fork with those updates to the Podfile - thank you @ueshiba !

**Comment by t0mmar** [comment]
@ueshiba I'm not sure if this is my local env setup issue or not, but when building for development on a device, I'm getting these errors on pod PhaseScriptExecution about "Permission denied" when it tries to copy some file... have you seen these before? (I don't get these when debugging in a simulator)

![Screen Shot 2020-12-18 at 12 41 29 PM](https://user-images.githubusercontent.com/45108654/102649659-31d14a00-412f-11eb-9d06-b98814a0e0d9.png)

[Build PIA VPN_2020-12-18T12-44-32.txt](https://github.com/pia-foss/vpn-ios/files/5717550/Build.PIA.VPN_2020-12-18T12-44-32.txt)

**Comment by t0mmar** [comment]
@ueshiba Have you seen the above errors before? Is there is a magic "build twice" procedure or something similar to help me get passed these errors?

**Comment by t0mmar** [comment]
I was able to get passed these errors! I'm not sure exactly what fixed it but I:
- updated MBP to latest OS
- used XCode 12.2 (as before)
- moved my sources into my "home" folder so they are not nested so deeply
- updated Android Studio to latest stable version 4.1.1 (updated SDKs and Kotlin plugin)

With those changes I can build and run on my dev phone.
