### ISSUE TITLE
Pod Install Issue

### ISSUE THREAD

**Issue by vaifllc** [pia-foss/vpn-ios#17]
Hello, i keep getting this error.

[!] Error installing PIAAccountModule
[!] Failed to download 'PIAAccountModule': [!] /usr/local/bin/git clone git@gitlab.kape.com:pia-mobile/shared/account.git /var/folders/0d/wfnhw6qd1573tf3zy5c1tws80000gn/T/d20210722-30783-nfpspg --template=

Cloning into '/var/folders/0d/wfnhw6qd1573tf3zy5c1tws80000gn/T/d20210722-30783-nfpspg'...
ssh: connect to host gitlab.kape.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by voynovia** [comment]
+1

**Comment by wfs498121294** [comment]
+1

**Comment by kvtien1996** [comment]
+1.
Anyone can help on this please.

**Comment by asparamancer** [comment]
+1 @ueshiba any assistance here?

**Comment by NitroJuice** [comment]
+1

**Comment by NitroJuice** [comment]
Please open gitlab.kape.com to world or copy repo to github

**Comment by AMJ-7** [comment]
bellow of lines:
```
# Pod groups

def shared_main_pods
    pod 'AlamofireImage'
```
replace it with current one: 
`pod "PIAAccountModule", :git => "#{$git_root}/#{$accounts_repo}"
`

**Comment by xv-laura-s** [comment]
Sorry for the very late response. This issue has been fixed in our latest version. I recommend you clone again this repo and try to build.
We have moved away from `Cocoapods` and we are managing dependencies with `SPM` instead. All the dependencies have also been moved to public repos.
