### ISSUE TITLE
Fails to log in with valid PIA credentials

### ISSUE THREAD

**Issue by t0mmar** [pia-foss/vpn-ios#3]
# Summary

App build from these sources fails to authenticate a valid PIA user whose credentials do work on the official PIA app from the App Store.

### Steps to reproduce
* build the app from these sources
* start running it on a device
* type in username and password, one that works on the official PIA app
* press Login button

### What is the current bug behaviour?
The call to log in fails with error "unauthorized"

### What is the expected correct behaviour?
Login succeeds because the credentials are good

### Relevant logs and/or screenshots
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/45108654/54061128-0634d800-41c5-11e9-8c06-ee0625ad0e60.png">

Network calls:

```
POST /api/client/v2/token HTTP/1.1
Host: www.privateinternetaccess.com
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Cookie: _pia_lm=en_en; u=6lch1c4z0562usuevnnp7wz1l
Connection: keep-alive
Accept: */*
User-Agent: PIA VPN/0.1.0 (*****; build:1; iOS 12.1.0) Alamofire/4.8.0
Accept-Language: en;q=1.0
Content-Length: 37
Accept-Encoding: gzip;q=1.0, compress;q=0.5

password=******&username=******

---

HTTP/1.1 200 OK
Server: Apache
Cache-Control: max-age=0, private, must-revalidate
X-XSS-Protection: 1; mode=block
X-Request-Id: 56eff9c2-a218-4b1f-8b2a-67a0f1f8eec4
X-Frame-Options: SAMEORIGIN
X-Runtime: 0.024810
X-Content-Type-Options: nosniff
ETag: W/"fdf66f0fb9f39970417c701cbbf81dbc"
Status: 200 OK
Cache-Control: max-age=3600
Expires: Sat, 09 Mar 2019 23:15:00 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
Content-Type: application/json; charset=utf-8
Date: Sat, 09 Mar 2019 22:15:00 GMT
Content-Length: 140
Connection: keep-alive

{"token":"66cb2b*****dca4194"}

---

GET /api/client/v2/account HTTP/1.1
Host: www.privateinternetaccess.com
Accept: */*
Cookie: _pia_lm=en_en; u=6lch1c4z0562usuevnnp7wz1l
User-Agent: PIA VPN/0.1.0 (*****; build:1; iOS 12.1.0) Alamofire/4.8.0
Accept-Language: en;q=1.0
Accept-Encoding: gzip;q=1.0, compress;q=0.5
Connection: keep-alive

---

HTTP/1.1 401 Unauthorized
Server: Apache
Cache-Control: no-cache
X-XSS-Protection: 1; mode=block
WWW-Authenticate: Token realm="Application"
X-Request-Id: 5275ed0a-863a-4e3d-9700-b498046d1423
X-Runtime: 0.005148
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Status: 401 Unauthorized
Cache-Control: max-age=3600
Expires: Sat, 09 Mar 2019 23:15:00 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
Content-Type: text/html; charset=utf-8
Date: Sat, 09 Mar 2019 22:15:00 GMT
Connection: close

HTTP Token: Access denied.


```

### Assignees and labels
( please add labels as applicable )    

- [ ] Patched
- [ ] Verified patch

**Comment by t0mmar** [comment]
Looking at the network logs, it looks like the credentials do get a token, but the call to `GET /api/client/v2/account` returns 401

**Comment by ueshiba** [comment]
Hi @t0mmar I can see an error in the console about the content type in the request. Did you make any change? Which Alamofire version are you using? 

Regards,
Jose.

**Comment by t0mmar** [comment]
Hi @ueshiba 

I believe the error in the console is regarding the **response** which comes back with Content-Type: text/html and I'm guessing the code is expecting JSON.  But that's already after it fails to authenticate.

I ran the above with Alamofire 4.8.0 and latest cocoapods, but this morning got exactly the same results with cocoapods 1.5.3 and Podfile.lock file as on this master branch (Alamofire 4.7.3).  The only changes I've made is to the app ids, code signing, and removed the Hotspothelper entitlement and code:

Here is the branch I'm building:
https://github.com/t0mmar/vpn-ios/tree/login_problem

I'm doing `pod install` with xcode7 then building with latest xcode.

**Comment by t0mmar** [comment]
I believe the problem is that the `GET  /api/client/v2/account` call doesn't send the token it obtained in the previous call in a header.  If I take the returned token and add it to the curl call, it succeeds:

```

curl -H 'Host: www.privateinternetaccess.com' -H 'Accept: */*' -H 'Cookie: _pia_lm=en_en; u=9u1p35c2dl6216gt9t1jw7xbq' -H 'User-Agent: PIA VPN/0.1.0 (sm.puri.librem.vpn; build:1; iOS 12.1.0) Alamofire/4.7.3' -H 'Accept-Language: en;q=1.0' -H 'Authorization: Token token="****"' --compressed 'https://www.privateinternetaccess.com/api/client/v2/account'


{"plan":"trial","product_id":null,"active":true,"canceled":false,"recurring":false,"needs_payment":false,"days_remaining":359,"renewable":false,"renew_url":"https://www.privateinternetaccess.com/pages/client-support/","expiration_time":1583330002,"expire_alert":false,"expired":false,"email":"*****"}
```

**Comment by t0mmar** [comment]
Indeed the problem was that the token was not being sent with the GET request.
That was because saving it to the keychain was failing, and that was failing because I missed updating teamId and appGroup in AppConstants.swift - all good now.  

This was an issue on my side.
