### ISSUE TITLE
Please provide code for App Store release version 3.1.0

### ISSUE THREAD

**Issue by t0mmar** [pia-foss/vpn-ios#8]
I see a new version 3.1.0 has been released on the app store but I don't see any code updates here.  I would really appreciate if you could release the new code soon.  Can you let me know when that might happen?

**Comment by t0mmar** [comment]
Any updates on this?

**Comment by articlecat** [comment]
Version 3.2.0 was released on November 7, while the repository release is stuck on version 3.0.1.

**Comment by ueshiba** [comment]
Sorry guys, we have internal processes we need to follow before we push the code. We just updated the repo to the latest release.
